#!/bin/bash

interface=$6
if [ -z "$interface" ]; then
    exit
fi

if ! /usr/bin/systemctl -q is-active dozenos-hostsd; then
    exit  # dozenos-hostsd is not running
fi

hostsd_client="/usr/bin/dozenos-hostsd-client"
$hostsd_client --delete-name-servers --tag "dhcp-$interface"
$hostsd_client --apply
